
runfolder_path: path/runfolder_name
samplesheet:  path/SampleSheet.csv

notification_mail: mail@mail.se

bcl2fastq_version: 2.17.1.14

barcode_mismatch: 1

extra:

#lanes:
#  - L001
#  - L002
#  - L003
#  - L004
