name: gms_somatic
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - fastp=0.20.1
  - bwa=0.7.17
  - samtools=1.9
  - bamtools=2.5.1
  - vardict=1.8.2
  - freebayes=1.3.2
  - parallel=20190522
  - bedtools=2.29
  - sed=4.7
  - gatk4=4.1.9.0
  - snakemake-wrapper-utils=0.1.3
  - bcftools=1.9
